name: gpii-l10n-bundles-experiments CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - run: npm install
    - run: npm run build
    - name: Commit file to compiledMessages branch
        uses: github-actions-x/commit@v2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: compiledMessages
          commit-message: "Updating compiledMessages"
          rebase: true
