name: gpii-l10n-bundles-experiments CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - run: npm install
    - run: npm run build
    - run: |
        echo "Checking ..."
        echo ${{ github.ref }}
    - name: Update compiledMessages file
      uses: alexesprit/action-update-file@v0.2.2
      with:
        file-path: build/gpii-app-messageBundles.json
        branch: compiledMessages
        github_token: ${{ secrets.GITHUB_TOKEN }}
